[project]
name = "mcp-server-pr-analyzer"
version = "0.1.0"
description = "MCP Server PR Analyzer is a tool designed to analyze pull requests for the MCP Server project, providing insights and feedback to contributors."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.26.0",
    "notion-client>=2.7.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
